# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classification.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='classification.proto',
  package='elections.mediawatch.io',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x63lassification.proto\x12\x17\x65lections.mediawatch.io\"\xb0\x01\n\x0cUserFeatures\x12\x11\n\tfollowers\x18\x01 \x01(\x03\x12\x0f\n\x07\x66riends\x18\x02 \x01(\x03\x12\x10\n\x08statuses\x18\x03 \x01(\x03\x12\x11\n\tfavorites\x18\x04 \x01(\x03\x12\r\n\x05lists\x18\x05 \x01(\x03\x12\x0b\n\x03\x66\x66r\x18\x06 \x01(\x01\x12\x0c\n\x04stfv\x18\x07 \x01(\x01\x12\r\n\x05\x66stfv\x18\x08 \x01(\x01\x12\r\n\x05\x64\x61tes\x18\t \x01(\x01\x12\x0f\n\x07\x61\x63tions\x18\n \x01(\x01\")\n\tUserClass\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\"\x9c\x01\n\x05Model\x12\x0e\n\x06\x61\x63tive\x18\x01 \x01(\x02\x12\x0b\n\x03\x62ot\x18\x02 \x01(\x02\x12\x12\n\ninfluencer\x18\x03 \x01(\x02\x12\x0b\n\x03new\x18\x04 \x01(\x02\x12\x0e\n\x06normal\x18\x05 \x01(\x02\x12\r\n\x05other\x18\x06 \x01(\x02\x12\x11\n\tretweeter\x18\x07 \x01(\x02\x12\x12\n\nsuper_user\x18\x08 \x01(\x02\x12\x0f\n\x07unknown\x18\t \x01(\x02\x32i\n\x0e\x43lassification\x12W\n\x08\x43lassify\x12%.elections.mediawatch.io.UserFeatures\x1a\".elections.mediawatch.io.UserClass\"\x00\x62\x06proto3')
)




_USERFEATURES = _descriptor.Descriptor(
  name='UserFeatures',
  full_name='elections.mediawatch.io.UserFeatures',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='followers', full_name='elections.mediawatch.io.UserFeatures.followers', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='friends', full_name='elections.mediawatch.io.UserFeatures.friends', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='statuses', full_name='elections.mediawatch.io.UserFeatures.statuses', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='favorites', full_name='elections.mediawatch.io.UserFeatures.favorites', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lists', full_name='elections.mediawatch.io.UserFeatures.lists', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ffr', full_name='elections.mediawatch.io.UserFeatures.ffr', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stfv', full_name='elections.mediawatch.io.UserFeatures.stfv', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fstfv', full_name='elections.mediawatch.io.UserFeatures.fstfv', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dates', full_name='elections.mediawatch.io.UserFeatures.dates', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actions', full_name='elections.mediawatch.io.UserFeatures.actions', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=226,
)


_USERCLASS = _descriptor.Descriptor(
  name='UserClass',
  full_name='elections.mediawatch.io.UserClass',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='elections.mediawatch.io.UserClass.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='elections.mediawatch.io.UserClass.score', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=269,
)


_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='elections.mediawatch.io.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='active', full_name='elections.mediawatch.io.Model.active', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bot', full_name='elections.mediawatch.io.Model.bot', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='influencer', full_name='elections.mediawatch.io.Model.influencer', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new', full_name='elections.mediawatch.io.Model.new', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='normal', full_name='elections.mediawatch.io.Model.normal', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='other', full_name='elections.mediawatch.io.Model.other', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='retweeter', full_name='elections.mediawatch.io.Model.retweeter', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='super_user', full_name='elections.mediawatch.io.Model.super_user', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unknown', full_name='elections.mediawatch.io.Model.unknown', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=428,
)

DESCRIPTOR.message_types_by_name['UserFeatures'] = _USERFEATURES
DESCRIPTOR.message_types_by_name['UserClass'] = _USERCLASS
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserFeatures = _reflection.GeneratedProtocolMessageType('UserFeatures', (_message.Message,), dict(
  DESCRIPTOR = _USERFEATURES,
  __module__ = 'classification_pb2'
  # @@protoc_insertion_point(class_scope:elections.mediawatch.io.UserFeatures)
  ))
_sym_db.RegisterMessage(UserFeatures)

UserClass = _reflection.GeneratedProtocolMessageType('UserClass', (_message.Message,), dict(
  DESCRIPTOR = _USERCLASS,
  __module__ = 'classification_pb2'
  # @@protoc_insertion_point(class_scope:elections.mediawatch.io.UserClass)
  ))
_sym_db.RegisterMessage(UserClass)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), dict(
  DESCRIPTOR = _MODEL,
  __module__ = 'classification_pb2'
  # @@protoc_insertion_point(class_scope:elections.mediawatch.io.Model)
  ))
_sym_db.RegisterMessage(Model)



_CLASSIFICATION = _descriptor.ServiceDescriptor(
  name='Classification',
  full_name='elections.mediawatch.io.Classification',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=430,
  serialized_end=535,
  methods=[
  _descriptor.MethodDescriptor(
    name='Classify',
    full_name='elections.mediawatch.io.Classification.Classify',
    index=0,
    containing_service=None,
    input_type=_USERFEATURES,
    output_type=_USERCLASS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLASSIFICATION)

DESCRIPTOR.services_by_name['Classification'] = _CLASSIFICATION

# @@protoc_insertion_point(module_scope)
